server:
  port: 8082

spring:
  application:
    name: service-transrecord
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/bank?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


